controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

    # config/routes.yaml

contact-us:
    path: /contact-us
    controller: App\Controller\FirstController::index
    methods: GET|POST

